package com.fixhomi.auth.service.notification;

/**
 * Interface for SMS OTP operations.
 * OTP generation and verification is handled locally by the caller.
 * Implementations are responsible only for delivering the SMS.
 */
public interface SmsService {

    /**
     * Send an OTP via SMS. The OTP is generated by the caller.
     *
     * @param phoneNumber recipient phone number
     * @param otp the OTP code to send
     * @return true if SMS was sent successfully
     */
    boolean sendOtp(String phoneNumber, String otp);

    /**
     * Send phone verification success notification (optional).
     *
     * @param phoneNumber recipient phone number
     * @return true if SMS was sent successfully
     */
    default boolean sendVerificationSuccess(String phoneNumber) {
        return true;
    }
}
